# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorial7',
                'doc_host': 'https://ConorOBrien-Foxx.github.io',
                'git_url': 'https://github.com/ConorOBrien-Foxx/tutorial7',
                'lib_path': 'tutorial7'},
  'syms': {'tutorial7.core': {'tutorial7.core.foo': ('core.html#foo', 'tutorial7/core.py')}}}